const tags = {
    ["Кор-во Даггерфолл"] : 'sea_east',
    ["Северный Камлорн"] : 'sea_east-north',
    ["Кор-во Вэйрест"] : 'sea_east',
    ["Южный Камлорн"] : 'sea_east',
    ["Кор-во Шорнхельм"] : 'sea_east',
    ["Кор-во Нортпойнт"] : 'sea_east-north',
    ["Кор-во Фаррун"] : 'sea_east-north',
    ["Кор-во Джеханна"] : 'sea_east-north',
    ["Кор-во Эвермор"] : 'sea_east',

    ["Хаафингар"] : 'sea_north',
    ["Предел"] : 'sea_north',
    ["Вайтран"] : 'sea_north',
    ["Хьялмарк"] : 'sea_north',
    ["Фолкрит"] : 'sea_north',
    ["Рифт"] : 'sea_north',
    ["Истмарк"] : 'sea_north',
    ["Винтерхолд"] : 'sea_north',
    ["Белый Берег"] : 'sea_north',

    ["Редоран"] : 'sea_west-north',
    ["Солстхейм"] : 'sea_north',
    ["Тель Митрин"] : 'sea_west-north',
    ["Острова Телванни"] : 'sea_west-north',
    ["Горы Боэтии"] : 'sea_west-north',
    ["Южный Телванни"] : 'sea_west-north',
    ["Индорил"] : 'sea_west',
    ["Южный Индорил"] : 'sea_west',
    ["Садрас"] : 'sea_west-north',

    ["Нага"] : 'sea_west',
    ["Торн"] : 'sea_west',
    ["Топкие болота"] : 'sea_west',
    ["Паатру"] : 'sea_west-south',
    ["Ан-зайлиль"] : 'sea_west-south',
    ["Гидеон"] : 'sea_west',
    ["Соулрест"] : 'sea_west-south',
    ["Лилмот"] : 'sea_west-south',

    ["Орсиниум"] : 'sea_east',
    ["Республика Драгонстар"] : 'sea_east',
    ["Республика Элинир"] : 'sea_east',
    ["Республика Рихад"] : 'sea_east',
    ["Регион Танет"] : 'sea_east',
    ["Регион Гилан"] : 'sea_east',
    ["Остров Стросс м'кай"] : 'sea_east',
    ["Регион Хегат"] : 'sea_east',
    ["Сентинель и Алик'р"] : 'sea_east',
    ["Южный Скавен"] : 'sea_east',
    ["Бангкорай"] : 'sea_east',

    ["Графство Брума"] : 'sea_center',
    ["Графство Коррол"] : 'sea_center',
    ["Графство Скинград"] : 'sea_center',
    ["Графство Кватч"] : 'sea_east',
    ["Графство Анвил"] : 'sea_east',
    ["Городской остров"] : 'sea_center',
    ["Графство Бравил"] : 'sea_center',
    ["Графство Лейавин"] : 'sea_south',
    ["Графство Чейдинхол"] : 'sea_center',

    ["Северная Анеквина"] : 'sea_south',
    ["Западная Анеквина"] : 'sea_south',
    ["ГГ Риммен"] : 'sea_south',
    ["Пустыня Эльсвейра"] : 'sea_south',
    ["Регион Коринф"] : 'sea_south',
    ["Тенмарские леса"] : 'sea_south',
    ["Полуостров Куинравл"] : 'sea_south',

    ["Северный Валенвуд"] : 'sea_east-south',
    ["Сильвенар"] : 'sea_east-south',
    ["Зелёный лес"] : 'sea_east-south',
    ["Западный мыс"] : 'sea_east-south',
    ["Затонувший берег"] : 'sea_east-south',
    ["Длинный берег"] : 'sea_east-south',
    ["Восточный Валенвуд"] : 'sea_east-south',

    ["Северный Ауридон"] : 'sea_east-south',
    ["Южный Ауридон"] : 'sea_east-south',
    ["Шиммерен"] : 'sea_east-south',
    ["Область Клаудрест"] : 'sea_east-south',
    ["Оррери"] : 'sea_east-south',
    ["Варилисс"] : 'sea_east-south',
    ["Восточный полуостров"] : 'sea_east-south',
    ["Регион Алинор"] : 'sea_east-south',
}

export const seaList = ['sea_north',
    'sea_east-north',
    'sea_east',
    'sea_east-south',
    'sea_south',
    'sea_west-south',
    'sea_west-north',
    'sea_center']

export default tags