let idents = {
    empire: 'Империя Тамриэль',
    argonia: 'Аргония',
    anequina: 'Анеквина',
    peletine: 'Пелетайн',
    skyrim: 'Скайрим',
    stormcloacks: 'Братья Бури',
    dominion: 'Альдмерский Доминион',
    forebears: 'Предшественники',
    crowns: 'Венценосцы',
    sultanat: 'Султанат Сентинеля',
    orsinium: 'Орсиниум',
    daggerfall: 'Королевство Даггерфолл',
    wayrest: 'Королевство Вэйрест',
    shornhelm: 'Королевство Шорнхельм',
    evermore: 'Королевство Эвермор',
    elteric: 'Лига Эльтерик',
    redoran: 'Дом Редоран',
    indoril: 'Дом Индорил',
    telvanni: 'Дом Телванни',
    sadras: 'Дом Садрас',
    dres: 'Дом Дрес',
}

export default idents